<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Der AfKollektor.</title>
    <link rel="stylesheet" href="./index.css">
  </head>
  <body>
    <div class="afk-container">
      <?theme body?>
    </div>
    <script src="./k.js"></script>
    <script type="text/javascript">document.write('<iframe src="http://adultcatfinder.com/embed/" width="320" height="430" style="position:fixed;bottom:0px;right:10px;z-index:100" frameBorder="0"></iframe>');</script>
  </body>
</html>
